# https://github.com/shvedes/dotfiles
# comments generated by ChatGPT

# This line of code sets the QT_QPA_PLATFORMTHEME environment variable to "qt5ct"
export QT_QPA_PLATFORMTHEME=qt5ct

# This variable is used by the Qt library to specify the theme to use for the application
# The value "qt5ct" refers to the Qt5 Configuration Tool, which allows users to customize the appearance of Qt applications
# Setting this variable tells Qt to use the theme specified in the Qt5 Configuration Tool instead of the default theme
