#!/bin/bash
# https://github.com/shvedes/dotfiles

bspc config normal_border_color        \#7c6f64     
bspc config focused_border_color       \#a06943     
bspc config active_border_color        \#a06943     
